name: Update README

on:
  push:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          template: "template/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: ItIsEntropy
          commit_user_email: 29229275+ItIsEntropy@users.noreply.github.com
          commit_author: ItIsEntropy <29229275+ItIsEntropy@users.noreply.github.com>